def artifactory_name = "kristianj"
def artifactory_repo = "includeos-develop"
def repo_url = 'https://github.com/hioa-cs/IncludeOS.git'
def repo_branch = 'conan'

def conan_user = 'includeos'
def conan_channel = 'tools'

pipeline {
  agent {
    label 'conan_pipe_worker'
  }

  // should create a library for these lists of values
  parameters {
    string(name: 'Libraries', defaultValue: '')
    string(name: 'LibLocation', defaultValue: '')
    string(name: 'Versions', defaultValue: '')
    string(name: 'Build_types', defaultValue: 'Release, Debug')
    string(name: 'Target_Architectures', defaultValue: 'x86_64, x86')
    string(name: 'Target_OS', defaultValue: 'Linux')
    string(name: 'Profiles', defaultValue: 'clang-6.0-linux-i386, clang-6.0-linux-x86_64')
    // keeping compiler version out of this, assuming it will be part of the profiles
    string(name: 'CompilerVer', defaultValue: '6.0') //clang version
  }

  stages {
      stage('Build') {
        steps {
          // should check if size of parameter is one, then no need to remove quotations
          script {
            def libraries = "${params.Libraries}"
            def versions = "${params.Versions}"
            def target_os = "${params.Target_OS}"
            def compiler_version = "${params.CompilerVer}"
            def lib_location = "${params.LibLocation}"
            def target_architectures = "${params.Target_Architectures}".replaceAll("\\s", "").split(',')
            def build_types = "${params.Build_types}".replaceAll("\\s", "").split(',')
            def profiles = "${params.Profiles}".replaceAll("\\s", "").split(',')

            currentBuild.description = "${libraries}/${versions} \
                                          profile: ${profiles} \
                                          build_type: ${build_types} \
                                          branch: ${GIT_BRANCH}
                                          "
            def builds = [:]
            def conan_file
            // gets only the taget arch defined inside the profile
            // def get_built_arch = `conan profile show ${profiles} | grep "arch_build=*" | cut -f2 -d=`

              for (prof in profiles) {
                  for (t_arch in target_architectures) {

              //      if (arch = "${get_built_arch}");
                //    then
                  //      t_arch = arch
                  //  fi

                    for (build in build_types) {
                      String buildName = "${libraries}-${build}-${t_arch}-${prof}"

                      builds[buildName] = {
                        node('conan_pipe_worker') {
                          stage(buildName){
                                  git branch: repo_branch, url: repo_url
                                  sh """
                                      if [ -z "${lib_location}" ];
                                      then
                                        if [ -d "conan/${libraries}/${versions}" ];
                                        then
                                          echo "creating ${libraries}/${versions}"
                                          conan create conan/${libraries}/${versions} \
                                          -s build_type=${build} \
                                          -pr ${prof} ${conan_user}/${conan_channel}
                                        else
                                          echo "creating ${libraries}"
                                          conan create conan/${libraries} \
                                          -s build_type=${build} \
                                          -pr ${prof} ${libraries}/${versions}@${conan_user}/${conan_channel}
                                        fi
                                      elif [ -n "${lib_location}" ];
                                      then
                                        echo "creating ${lib_location}/${libraries}"
                                        conan create conan/${lib_location}/${libraries} \
                                        -s build_type=${build} \
                                        -pr ${prof} ${libraries}/${versions}@${conan_user}/${conan_channel}
                                      fi
                                  """
                          }
                        }
                      }
                    }
                  }
              }
            parallel builds
          }
        }
      }
  }
}
