def artifactory_name = "kristianj"
def artifactory_repo = "includeos-develop"
def repo_url = 'https://github.com/hioa-cs/IncludeOS.git'
def repo_branch = 'conan'

def conan_user = 'includeos'
def conan_channel = 'tools'

pipeline {
  agent {
    label 'conan_pipe_worker'
  }

  // should create a library for these lists of values
  parameters {
    string(name: 'Tools', defaultValue: '')
    string(name: 'ToolLocation', defaultValue: '')
    string(name: 'Versions', defaultValue: '')
    string(name: 'Build_types', defaultValue: 'Release, Debug')
    string(name: 'Target_OS', defaultValue: 'Linux')
    string(name: 'Profiles', defaultValue: 'clang-6.0-linux-i386, clang-6.0-linux-x86_64, gcc-7.3.0-linux-x86_64, gcc-8.2.0-linux-i386, gcc-8.2.0-linux-x86_64')
  }

  stages {
      stage('Build') {
        steps {
          // should check if size of parameter is one, then no need to remove quotations
          script {
            def tools = "${params.Tools}"
            def versions = "${params.Versions}"
            def target_os = "${params.Target_OS}"
            def tool_loc = "${params.ToolLocation}"
            def build_types = "${params.Build_types}".replaceAll("\\s", "").split(',')
            def profiles = "${params.Profiles}".replaceAll("\\s", "").split(',')

            currentBuild.description = "building: ${tools}/${versions} \
                                          profile: ${profiles} \
                                          branch: ${GIT_BRANCH}, "
            def builds = [:]

              for (prof in profiles) {
                    for (build in build_types) {
                      String buildName = "${tools}-${build}-${prof}"

                      builds[buildName] = {
                        node('conan_pipe_worker') {
                          stage(buildName){
                                  git branch: repo_branch, url: repo_url
                                  sh """
                                      if [ -z "${tool_loc}" ];
                                      then
                                        if [ -d "conan/${tools}/${versions}" ];
                                        then
                                          echo "creating ${tools}/${versions}"
                                          conan create conan/${tools}/${versions} \
                                          -s build_type=${build} \
                                          -pr ${prof} ${conan_user}/${conan_channel} --build missing
                                        else
                                          echo "creating ${tools}"
                                          conan create conan/${tools} \
                                          -s build_type=${build} \
                                          -pr ${prof} ${tools}/${versions}@${conan_user}/${conan_channel} --build missing
                                        fi
                                      elif [ -n "${tool_loc}" ];
                                      then
                                        echo "creating ${tool_loc}/${tools}"
                                        conan create conan/${tool_loc}/${tools} \
                                        -s build_type=${build} \
                                        -pr ${prof} ${tools}/${versions}@${conan_user}/${conan_channel} --build missing
                                      fi
                                  """
                          }
                        }
                      }
                    }
                  }
            parallel builds
          }
        }
      }
  }
}
